export const viajes = [
  {
    continente: "EUROPA",
    nombre: "Alemania Mágica",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 7,
    fechas:
      "14 de Junio, 12 de Julio, 2 de Agosto, 6 de Septiembre y 11 de Octubre",
    mes: "Junio, Julio, Agosto, Septiembre y Octubre",
    ciudadSalida: "Valencia",
    precioHabDoble: 1580.0,
    precioIndividual: 2250.0,
    proveedor: "Kannak",
    linkWeb: "Alemania Mágica (con vuelos incluidos)",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Alemania Romántica de Múnich a Berlín",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-07-11",
    mes: "Julio",
    ciudadSalida: "Valencia",
    precioHabDoble: 1700.0,
    precioIndividual: 1950.0,
    proveedor: "Special Tours",
    linkWeb:
      "Circuito Alemania Romántica de Múnich a Berlín (Vuelos Especiales) desde 1.343 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Austria",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas:
      "1 de Junio, 15 de Junio, 13 de Julio, 10 de Agosto, 7 de Septiembre, 21 de Septiembre, 5 de Octubre",
    mes: "Junio, Julio, Agosto, Septiembre y Octubre",
    ciudadSalida: "Valencia",
    precioHabDoble: 1850.0,
    precioIndividual: 2390.0,
    proveedor: "Kannak",
    linkWeb: "Lo Mejor de Austria (con vuelos incluidos)",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Bretaña y Normandía",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-07-04",
    mes: "Julio",
    ciudadSalida: "Valencia",
    precioHabDoble: 1450.0,
    precioIndividual: 1800.0,
    proveedor: "Special Tours",
    linkWeb:
      "Circuito Maravillas de Bretaña y Normandía (Vuelos Especiales) desde 1.206 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Croacia y Eslovenia",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-06-30",
    mes: "Junio",
    ciudadSalida: "Madrid",
    precioHabDoble: 1890.0,
    precioIndividual: 2360.0,
    proveedor: "Itinae",
    linkWeb: "ITINAE - B2B LO MEJOR DE CROACIA Y ESLOVENIA",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Croacia, Bosnia y Eslovenia",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 10,
    fechas: "16 de Junio, 14 de Julio, 11 de Agosto, 1 de Septiembre",
    mes: "Junio, Julio, Agosto, Septiembre",
    ciudadSalida: "Valencia",
    precioHabDoble: 2700.0,
    precioIndividual: 3620.0,
    proveedor: "Kannak",
    linkWeb: "Gran Tour de Croacia Bosnia y Eslovenia (con vuelos incluidos)",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Escocia y tierras altas",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-08-11",
    mes: "Agosto",
    ciudadSalida: "Valencia",
    precioHabDoble: 3100.0,
    precioIndividual: 3900.0,
    proveedor: "Special Tours",
    linkWeb:
      "Circuito Escocia: Tierras Altas (Vuelos Especiales) desde 2.227 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Escocia: castillos, lagos y tierras altas",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-08-11",
    mes: "Agosto",
    ciudadSalida: "Valencia",
    precioHabDoble: 2650.0,
    precioIndividual: 3500.0,
    proveedor: "Special Tours",
    linkWeb:
      "Circuito Escocia: Castillos, Lagos y Tierras Altas (Vuelos Especiales) desde 2.340 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Eslovenia, Península de Istria y Véneto",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-07-19",
    mes: "Julio",
    ciudadSalida: "Valencia",
    precioHabDoble: 2200.0,
    precioIndividual: 3100.0,
    proveedor: "Special Tours",
    linkWeb:
      "Circuito Maravillas de Eslovenia,Peninsula de Istria y Veneto (Vuelos Especiales) desde 1.912 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Eslovenia, Península de Istria y Véneto",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "26 de Julio y 23 de Agosto",
    mes: "Julio y Agosto",
    ciudadSalida: "Madrid",
    precioHabDoble: 2200.0,
    precioIndividual: 3100.0,
    proveedor: "Special Tours",
    linkWeb: "Circuitos",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Estocolmo y Fiordos Noruegos",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 9,
    fechas: "8 junio, 6 julio, 10 agosto y 7 septiembre",
    mes: "Junio",
    ciudadSalida: "Valencia",
    precioHabDoble: 2300.0,
    precioIndividual: 3100.0,
    proveedor: "Kannak",
    linkWeb:
      "https://www.kannak.es/es-es/travel/estocolmo-y-fiordos-noruegos-con-vuelos?tags=WTT323&origins=VLC",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Fiordos y oslo",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-08-03",
    mes: "Agosto",
    ciudadSalida: "Valencia",
    precioHabDoble: 2500.0,
    precioIndividual: 3200.0,
    proveedor: "Special Tours",
    linkWeb: "Circuito Fiordos y Oslo (Vuelos Especiales) desde 2.232 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Irlanda",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-07-31",
    mes: "Julio",
    ciudadSalida: "Madrid",
    precioHabDoble: 1950.0,
    precioIndividual: 2430.0,
    proveedor: "Itinae",
    linkWeb: "ITINAE - B2B LO MEJOR DE IRLANDA",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Italia clásica",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 7,
    fechas: "7 junio, 5 julio, 2 agosto, 6 septiembre",
    mes: "Junio, Julio, Agosto y Septiembre",
    ciudadSalida: "Valencia",
    precioHabDoble: 1400.0,
    precioIndividual: 2000.0,
    proveedor: "Kannak",
    linkWeb:
      "https://www.kannak.es/es-es/travel/italia-clasica-con-vuelos-incluidos?tags=WTT323&origins=VLC",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Madeira",
    tipologia: "plaza_a_plaza",
    dias: 8,
    fechas: "desde junio a septiembre",
    mes: "Junio",
    ciudadSalida: "Valencia",
    precioHabDoble: 1200.0,
    precioIndividual: 1500.0,
    proveedor: null,
    linkWeb: null,
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Múnich, Praga y Berlín",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-07-11",
    mes: "Julio",
    ciudadSalida: "Valencia",
    precioHabDoble: 1650.0,
    precioIndividual: 2100.0,
    proveedor: "Special Tours",
    linkWeb:
      "Circuito Descubre Múnich, Praga y Berlín (Vuelos Especiales) desde 1.275 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Norte de Italia, Lagos y Véneto",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-07-19",
    mes: "Julio",
    ciudadSalida: "Valencia",
    precioHabDoble: 1650.0,
    precioIndividual: 2150.0,
    proveedor: "Special Tours",
    linkWeb:
      "Circuito Paisajes del Norte de Italia, Lagos y Véneto (Vuelos Especiales) desde 1.535 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Norte de Italia, Lagos y Véneto",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-08-23",
    mes: "Agosto",
    ciudadSalida: "Madrid",
    precioHabDoble: 1650.0,
    precioIndividual: 2150.0,
    proveedor: "Special Tours",
    linkWeb:
      "Circuito Paisajes del Norte de Italia, Lagos y Véneto (Vuelos Especiales) desde 1.535 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Paisajes de escocia",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-08-11",
    mes: "Agosto",
    ciudadSalida: "Valencia",
    precioHabDoble: 2900.0,
    precioIndividual: 3800.0,
    proveedor: "Special Tours",
    linkWeb: "Circuito Paisajes de Escocia (Vuelos Especiales) desde 2.134 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Paises Bajos",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 7,
    fechas:
      "5 de Junio, 3 de Julio, 7 de Agosto, 11 de Septiembre, 2 de Octubre",
    mes: "Junio, Julio, Agosto, Septiembre, Octubre",
    ciudadSalida: "Madrid",
    precioHabDoble: 1520.0,
    precioIndividual: 2100.0,
    proveedor: "Kannak",
    linkWeb: "Lo mejor de los Países Bajos (con vuelos incluidos)",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "París",
    tipologia: null,
    dias: 5,
    fechas: "Mayo y Junio",
    mes: "Mayo",
    ciudadSalida: null,
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Mundiplan",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Paris, Normandía y Loira",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-09-05",
    mes: "Septiembre",
    ciudadSalida: "Madrid",
    precioHabDoble: 1650.0,
    precioIndividual: 2050.0,
    proveedor: "Itinae",
    linkWeb: "ITINAE - B2B PARIS, NORMANDIA Y CASTILLOS DEL LOIRA",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Portugal",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 7,
    fechas: "2026-03-29",
    mes: "Marzo",
    ciudadSalida: "Valencia",
    precioHabDoble: 750.0,
    precioIndividual: 1000.0,
    proveedor: "Interrias",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Portugal",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 5,
    fechas: "2026-04-02",
    mes: "Abril",
    ciudadSalida: "Valencia",
    precioHabDoble: 975.0,
    precioIndividual: 1175.0,
    proveedor: "Marsol",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Polonia",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas:
      "8 de Junio, 20 de Julio, 17 de Agosto, 14 de Septiembre, 12 de Octubre.",
    mes: "Junio, Julio, Agosto, Septiembre, Octubre",
    ciudadSalida: "Valencia",
    precioHabDoble: 1650.0,
    precioIndividual: 2100.0,
    proveedor: "Kannak",
    linkWeb: "Perlas de Polonia (con vuelos incluidos)",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Praga",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 5,
    fechas: "Abril y Mayo",
    mes: "Abril",
    ciudadSalida: null,
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Mundiplan",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Praga y budapest",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-08-18",
    mes: "Agosto",
    ciudadSalida: "Valencia",
    precioHabDoble: 1550.0,
    precioIndividual: 2000.0,
    proveedor: "Special Tours",
    linkWeb: "Circuito Praga y Budapest (Vuelos Especiales) desde 1.174 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Roma",
    tipologia: null,
    dias: 5,
    fechas: "Mayo",
    mes: "Mayo",
    ciudadSalida: null,
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Mundiplan",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Rumanía histórica",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-07-26",
    mes: "Julio",
    ciudadSalida: "Valencia",
    precioHabDoble: 1950.0,
    precioIndividual: 2400.0,
    proveedor: "Special Tours",
    linkWeb: "Circuito Rumanía Histórica (Vuelos Especiales) desde 1.607 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Rumanía Romántica",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-07-26",
    mes: "Julio",
    ciudadSalida: "Valencia",
    precioHabDoble: 2000.0,
    precioIndividual: 2500.0,
    proveedor: "Special Tours",
    linkWeb: "Circuito Rumania Romántica (Vuelos Especiales) desde 1.756 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Sicilia",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-09-15",
    mes: "Septiembre",
    ciudadSalida: "Madrid",
    precioHabDoble: 1550.0,
    precioIndividual: 1950.0,
    proveedor: "Itinae",
    linkWeb: "ITINAE - B2B SICILIA MARAVILLOSA",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Suiza",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-07-24",
    mes: "Julio",
    ciudadSalida: "Madrid",
    precioHabDoble: 1895.0,
    precioIndividual: 2380.0,
    proveedor: "Itinae",
    linkWeb: "ITINAE - B2B SUIZA AL COMPLETO",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Toscana Norte de Italia y Véneto",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-07-19",
    mes: "Julio",
    ciudadSalida: "Valencia",
    precioHabDoble: 1600.0,
    precioIndividual: 1950.0,
    proveedor: "Special Tours",
    linkWeb:
      "Circuito Paisajes de la Toscana,Norte de Italia y Veneto (Vuelos Especiales) desde 1.354 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Toscana Norte de Italia y Véneto",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "26 de Julio y 23 Agosto",
    mes: "Julio y Agosto",
    ciudadSalida: "Madrid",
    precioHabDoble: 1600.0,
    precioIndividual: 1950.0,
    proveedor: "Special Tours",
    linkWeb: "Circuitos",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Valle de Loira y Normandía",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-07-04",
    mes: "Julio",
    ciudadSalida: "Valencia",
    precioHabDoble: 1600.0,
    precioIndividual: 2100.0,
    proveedor: "Special Tours",
    linkWeb:
      "Circuito Maravillas del Vallle del Loira y Normandía (Vuelos Especiales) desde 1.274 €.",
    activo: true,
  },
  {
    continente: "EUROPA",
    nombre: "Capitales imperiales",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 7,
    fechas: "13 junio, 11 julio, 15 agosto y 19 septiembre",
    mes: "Junio",
    ciudadSalida: "Valencia",
    precioHabDoble: 1400.0,
    precioIndividual: 1900.0,
    proveedor: "Kannak",
    linkWeb:
      "https://www.kannak.es/es-es/travel/capitales-imperiales-con-vuelo-incluido?tags=WTT323&origins=VLC",
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "China",
    tipologia: "cupo",
    dias: 10,
    fechas: "2026-08-12",
    mes: "Agosto",
    ciudadSalida: "Valencia",
    precioHabDoble: 2850.0,
    precioIndividual: 3320.0,
    proveedor: "Destinos del Mundo",
    linkWeb:
      "Destinos del Mundo, Tour operador especialista en viajes a medida desde 2010 - Agencia de viajes",
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "China ¡Fin de año!",
    tipologia: "cupo",
    dias: 10,
    fechas: "2026-12-26",
    mes: "Diciembre",
    ciudadSalida: "Valencia",
    precioHabDoble: 2670.0,
    precioIndividual: 3150.0,
    proveedor: "Destinos del Mundo",
    linkWeb:
      "Destinos del Mundo, Tour operador especialista en viajes a medida desde 2010 - Agencia de viajes",
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Camboya",
    tipologia: "plaza_a_plaza",
    dias: 10,
    fechas: "Abril a diciembe (solo jueves)",
    mes: "Todo el año",
    ciudadSalida: "Madrid",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Destinos del Mundo",
    linkWeb:
      "Circuito Camboya Esencial desde Bangkok con Iberojet desde 2.116 €.",
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Corea",
    tipologia: "cupo",
    dias: 10,
    fechas: "19 de Julio, 2 de Agosto, 16 de agosto y 11 de octubre",
    mes: "Julio, Agosto, Octubre",
    ciudadSalida: "Valencia",
    precioHabDoble: 3650.0,
    precioIndividual: 4250.0,
    proveedor: "Destinos del Mundo",
    linkWeb:
      "Destinos del Mundo, Tour operador especialista en viajes a medida desde 2010 - Agencia de viajes",
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "India (Festival Diwali)",
    tipologia: "cupo",
    dias: 9,
    fechas: "2026-11-04",
    mes: "Noviembre",
    ciudadSalida: "Madrid",
    precioHabDoble: 1700.0,
    precioIndividual: 2170.0,
    proveedor: "Destinos del Mundo",
    linkWeb:
      "Destinos del Mundo, Tour operador especialista en viajes a medida desde 2010 - Agencia de viajes",
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Japon Matsumoto",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 12,
    fechas: "2 agosto, 14 septiembre, 3 y 16 noviembre y 26 diciembre",
    mes: "agosto, septiembre, octubre noviembre, diciembre",
    ciudadSalida: "Madrid/Valencia",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Destinos del Mundo",
    linkWeb:
      "https://www.destinosdelmundo.es/viajes/japon-matsumoto-cupos-2026",
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "India (Triángulo Dorado)",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "7 de Agosto y 4 de Septiembre",
    mes: "Septiembre",
    ciudadSalida: "Madrid",
    precioHabDoble: 1500.0,
    precioIndividual: 1700.0,
    proveedor: "Destinos del Mundo",
    linkWeb:
      "Destinos del Mundo, Tour operador especialista en viajes a medida desde 2010 - Agencia de viajes",
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Japón",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 11,
    fechas: "2026-06-18",
    mes: "Junio",
    ciudadSalida: "Madrid",
    precioHabDoble: 4100.0,
    precioIndividual: 4800.0,
    proveedor: "Itinae",
    linkWeb: "ITINAE - B2B JAPON ESPECTACULAR en Primavera",
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Japón en otoño",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 14,
    fechas: "2026-10-24",
    mes: "Octubre",
    ciudadSalida: "Madrid",
    precioHabDoble: 4000.0,
    precioIndividual: 5000.0,
    proveedor: "Viajar a Japón",
    linkWeb: "https://www.viajarajapon.com/otono-2026",
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Ruta de la Seda Urbekistan",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "Agosto-septiembre",
    mes: "Agosto",
    ciudadSalida: "Madrid",
    precioHabDoble: 1750.0,
    precioIndividual: 2100.0,
    proveedor: null,
    linkWeb: null,
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Turquía",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 4,
    fechas: "puente octubre",
    mes: "Octubre",
    ciudadSalida: "Valencia",
    precioHabDoble: 950.0,
    precioIndividual: 1170.0,
    proveedor: "Destinos del Mundo",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Turquía",
    tipologia: "cupo",
    dias: 6,
    fechas: null,
    mes: null,
    ciudadSalida: null,
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: null,
    linkWeb: null,
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Vietnam",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 12,
    fechas: "septiembre",
    mes: "Septiembre",
    ciudadSalida: "Valencia",
    precioHabDoble: 2100.0,
    precioIndividual: 2400.0,
    proveedor: null,
    linkWeb: null,
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Túrquia",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 9,
    fechas: "Agosto y Septiembre",
    mes: "Agosto",
    ciudadSalida: "Valencia",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Monturista",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Uzbekistan",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: null,
    fechas: null,
    mes: null,
    ciudadSalida: null,
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: null,
    linkWeb: null,
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Vietnam",
    tipologia: "plaza_a_plaza",
    dias: 8,
    fechas: "Abril a Diciembre (Martes y Sábados)",
    mes: "Todo el año",
    ciudadSalida: "Madrid",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Travel Plan",
    linkWeb:
      "Circuito Norte de Vietnam 8 días. Ext. Siem Reap 10 días. Ext. Bali 11 días. desde 1.326 €.",
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Tailandia",
    tipologia: "plaza_a_plaza",
    dias: 10,
    fechas: "Abril a Diciembre ( Solo jueves y pocos domingos)",
    mes: "Todo el año",
    ciudadSalida: "Madrid",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Travel Plan",
    linkWeb: "Circuito Tailandia a tu aire con Iberojet desde 903 €.",
    activo: true,
  },
  {
    continente: "ASIA",
    nombre: "Indonesia ( Bali)",
    tipologia: "plaza_a_plaza",
    dias: 11,
    fechas: "Abril a Junio y noviembre ( solo martes)",
    mes: "Junio y Noviembre",
    ciudadSalida: "Madrid",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Travel Plan",
    linkWeb: "Circuito Bali Encantado desde 1.508 €.",
    activo: true,
  },
  {
    continente: "AFRICA",
    nombre: "Egipto",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "salidas lunes",
    mes: "Todo el año",
    ciudadSalida: "Valencia",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: null,
    linkWeb: null,
    activo: true,
  },
  {
    continente: "AFRICA",
    nombre: "Egipto",
    tipologia: "cupo",
    dias: 8,
    fechas: "salidas Abirl a Dic los L, V, S",
    mes: "Todo el año",
    ciudadSalida: "Madrid",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Sara Tours",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "AFRICA",
    nombre: "Jordania",
    tipologia: "cupo",
    dias: 8,
    fechas: "Abril -Feb 2027 ( M, X, S,D)",
    mes: "Todo el año",
    ciudadSalida: "Madrid",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Saraya Tours",
    linkWeb:
      "https://www.sarayatours.es/reservar/jordania-con-desierto-8-dias_-2304?search_date=",
    activo: true,
  },
  {
    continente: "AFRICA",
    nombre: "Kenia",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 12,
    fechas: "2026-09-01",
    mes: "Septiembre",
    ciudadSalida: "Madrid",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Destinos del Mundo",
    linkWeb:
      "Destinos del Mundo, Tour operador especialista en viajes a medida desde 2010 - Agencia de viajes",
    activo: true,
  },
  {
    continente: "AFRICA",
    nombre: "Túnez",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-03-29",
    mes: "Marzo",
    ciudadSalida: "Madrid",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Destinos del Mundo",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "AFRICA",
    nombre: "Marruecos",
    tipologia: "cupo",
    dias: 8,
    fechas: "Abril a Dic ( todos los mart)",
    mes: "Todo el año",
    ciudadSalida: "Madrid",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Sara Tours",
    linkWeb: "Oferta circuito Ciudades Imperiales - Saraya Tours",
    activo: true,
  },
  {
    continente: "AFRICA",
    nombre: "Túnez",
    tipologia: "cupo",
    dias: 8,
    fechas: "2 y 23 Agosto",
    mes: "Agosto",
    ciudadSalida: null,
    precioHabDoble: 1475.0,
    precioIndividual: 1745.0,
    proveedor: "Destinos del Mundo",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "AFRICA",
    nombre: "Senegal",
    tipologia: "cupo",
    dias: 8,
    fechas: "2026-12-05",
    mes: "Diciembre",
    ciudadSalida: "Madrid",
    precioHabDoble: 1950.0,
    precioIndividual: 2205.0,
    proveedor: "Destinos del Mundo",
    linkWeb:
      "Destinos del Mundo, Tour operador especialista en viajes a medida desde 2010 - Agencia de viajes",
    activo: true,
  },
  {
    continente: "AFRICA",
    nombre: "Tanzania y Zanzibar",
    tipologia: "cupo",
    dias: 10,
    fechas: "2026-08-16",
    mes: "Agosto",
    ciudadSalida: "Valencia",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "Destinos del Mundo",
    linkWeb:
      "Destinos del Mundo, Tour operador especialista en viajes a medida desde 2010 - Agencia de viajes",
    activo: true,
  },
  {
    continente: "AFRICA",
    nombre: "Zanzibar",
    tipologia: "plaza_a_plaza",
    dias: 8,
    fechas: "Julio , Agoso y Sept ( Solo lunes)",
    mes: "Julio , Agoso y Sept ( Solo lunes)",
    ciudadSalida: "Madrid",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "NewBlue",
    linkWeb: "Zanzíbar - Essence",
    activo: true,
  },
  {
    continente: "AMERICA",
    nombre: "Canadá",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 8,
    fechas: "2026-08-15",
    mes: "Agosto",
    ciudadSalida: "Valencia",
    precioHabDoble: 2670.0,
    precioIndividual: 3200.0,
    proveedor: "TUI",
    linkWeb: "TUI SPAIN",
    activo: true,
  },
  {
    continente: "AMERICA",
    nombre: "Colombia",
    tipologia: "cupo",
    dias: 12,
    fechas: "2026-08-18",
    mes: "Agosto",
    ciudadSalida: "Madrid",
    precioHabDoble: 3800.0,
    precioIndividual: 4800.0,
    proveedor: "Destinos del Mundo",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "AMERICA",
    nombre: "Costa Rica Vive el Pura Vida y Guanacaste",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 12,
    fechas:
      "Julio 12 y 26                                      Agosto 2,9,16,30",
    mes: "Agosto",
    ciudadSalida: "Madrid",
    precioHabDoble: 2500.0,
    precioIndividual: 3000.0,
    proveedor: "Viva Tours",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "AMERICA",
    nombre: "Costa Rica Vive el Pura Vida y Manuel Antonio",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 12,
    fechas:
      "julio 19 y 26                                      Agosto 2,9,16,30",
    mes: "Agosto",
    ciudadSalida: "Madrid",
    precioHabDoble: 2450.0,
    precioIndividual: 2900.0,
    proveedor: "Viva Tours",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "AMERICA",
    nombre: "Perú",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 12,
    fechas:
      "Julio 15                                                    Agosto 3",
    mes: "Agosto",
    ciudadSalida: "Madrid",
    precioHabDoble: 3350.0,
    precioIndividual: 3750.0,
    proveedor: "Viva Tours",
    linkWeb: "Circuito Salidas Especiales Verano Descubre Perú desde 3.165 €.",
    activo: true,
  },
  {
    continente: "AMERICA",
    nombre: "Perú La Magia de la Montaña Arcoíris",
    tipologia: "plaza_a_plaza_en_grupo",
    dias: 14,
    fechas:
      "Julio 14 y 31                                  Agosto 16                                            Septiembre 1",
    mes: "Agosto",
    ciudadSalida: "Madrid",
    precioHabDoble: 3550.0,
    precioIndividual: 4000.0,
    proveedor: "Viva Tours",
    linkWeb: null,
    activo: true,
  },
  {
    continente: "AMERICA",
    nombre: "Perú Mágico",
    tipologia: "cupo",
    dias: 14,
    fechas: "2026-11-03",
    mes: "Noviembre",
    ciudadSalida: "Madrid",
    precioHabDoble: 3600.0,
    precioIndividual: 4180.0,
    proveedor: "Destinos del Mundo",
    linkWeb:
      "Destinos del Mundo, Tour operador especialista en viajes a medida desde 2010 - Agencia de viajes",
    activo: true,
  },
  {
    continente: "AMERICA",
    nombre: "Rivera Maya",
    tipologia: "plaza_a_plaza",
    dias: 8,
    fechas: "Abril 2026 hasta Enero 2027 Casi todos los días  semana",
    mes: "Todo el año",
    ciudadSalida: "Madrid/Valencia",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "NewBlue",
    linkWeb: "Riviera Maya - Essence",
    activo: true,
  },
  {
    continente: "AMERICA",
    nombre: "Punta cana",
    tipologia: "plaza_a_plaza",
    dias: 9,
    fechas: "Abril 2026 hasta Enero 2027 Casi todos los dias semana",
    mes: "Todo el año",
    ciudadSalida: "Madrid/Valencia",
    precioHabDoble: null,
    precioIndividual: null,
    proveedor: "NewBlue",
    linkWeb: "Punta Cana - Essence",
    activo: true,
  },
];
